/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thescrumbags.Classes;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jjn
 */
public class MenuFrame extends javax.swing.JFrame {

    Register r;

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
        r = Register.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        startSaleButton = new javax.swing.JButton();
        startRentalButton = new javax.swing.JButton();
        startReturnButton = new javax.swing.JButton();
        userManagementButton = new javax.swing.JButton();
        salePanel = new javax.swing.JPanel();
        saleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        saleCartTable = new javax.swing.JTable();
        saleCheckoutButton = new javax.swing.JButton();
        saleCartLabel = new javax.swing.JLabel();
        saleIdTextField = new javax.swing.JTextField();
        saleIdLabel = new javax.swing.JLabel();
        saleQtyTextField = new javax.swing.JTextField();
        saleQtyLabel = new javax.swing.JLabel();
        saleAddButton = new javax.swing.JButton();
        saleCancelButton = new javax.swing.JButton();
        saleRemoveButton = new javax.swing.JButton();
        saleTotalLabel = new javax.swing.JLabel();
        saleRemoveLabl = new javax.swing.JLabel();
        saleRemoveTextField = new javax.swing.JTextField();
        saleItemAddErrorPanel = new javax.swing.JPanel();
        itemAddErrorLabel = new javax.swing.JLabel();
        itemAddOkButton = new javax.swing.JButton();
        saleRemoveErrorPanel = new javax.swing.JPanel();
        removeErrorLabel = new javax.swing.JLabel();
        removeErrorOkButton = new javax.swing.JButton();
        rentPanel = new javax.swing.JPanel();
        rentLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        rentCartTable = new javax.swing.JTable();
        rentCheckoutButton = new javax.swing.JButton();
        rentCartLabel = new javax.swing.JLabel();
        rentIdTextField = new javax.swing.JTextField();
        rentIdLabel = new javax.swing.JLabel();
        rentQtyTextField = new javax.swing.JTextField();
        rentQtyLabel = new javax.swing.JLabel();
        rentAddButton = new javax.swing.JButton();
        rentCancelButton = new javax.swing.JButton();
        rentRemoveButton = new javax.swing.JButton();
        rentTotalLabel = new javax.swing.JLabel();
        rentRemoveLabel = new javax.swing.JLabel();
        rentRemoveTextField = new javax.swing.JTextField();
        rentPeriodLabel = new javax.swing.JLabel();
        rentPeriodPanel = new javax.swing.JPanel();
        rentPeriodPanelLabel = new javax.swing.JLabel();
        rentPeriodSpinner = new javax.swing.JSpinner();
        rentPeriodSetButton = new javax.swing.JButton();
        rentPeriodCancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cashOrCreditPanel = new javax.swing.JPanel();
        cashButton = new javax.swing.JButton();
        creditButton = new javax.swing.JButton();
        cashPanel = new javax.swing.JPanel();
        calcChangeButton = new javax.swing.JButton();
        cashReceivedTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cashPanelCancelButton = new javax.swing.JButton();
        changeLabel = new javax.swing.JLabel();
        cashDoneButton = new javax.swing.JButton();
        changeAmountLabel = new javax.swing.JLabel();
        cashErrorLabel = new javax.swing.JLabel();
        cashTotalLabel = new javax.swing.JLabel();
        rentRemoveErrorPanel = new javax.swing.JPanel();
        rentRemoveErrorLabel = new javax.swing.JLabel();
        rentRemoveErrorButton = new javax.swing.JButton();
        rentItemAddErrorPanel = new javax.swing.JPanel();
        rentItemAddErrorLabel = new javax.swing.JLabel();
        rentItemAddErrorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        menuLabel.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        menuLabel.setText("Main Menu");

        startSaleButton.setText("Start New Sale");
        startSaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startSaleButtonActionPerformed(evt);
            }
        });

        startRentalButton.setText("Start New Rental");
        startRentalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startRentalButtonActionPerformed(evt);
            }
        });

        startReturnButton.setText("Start New Return");

        userManagementButton.setText("User Management");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userManagementButton)
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(startReturnButton)
                        .addComponent(startRentalButton)
                        .addComponent(startSaleButton)))
                .addContainerGap(229, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {startRentalButton, startReturnButton, startSaleButton, userManagementButton});

        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(startSaleButton)
                .addGap(35, 35, 35)
                .addComponent(startRentalButton)
                .addGap(35, 35, 35)
                .addComponent(startReturnButton)
                .addGap(35, 35, 35)
                .addComponent(userManagementButton)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(menuPanel, "card2");

        saleLabel.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        saleLabel.setText("New Sale");

        saleCartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Description", "Unit Price", "Quantity", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(saleCartTable);

        saleCheckoutButton.setText("Checkout");
        saleCheckoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleCheckoutButtonActionPerformed(evt);
            }
        });

        saleCartLabel.setText("Customer Cart");

        saleIdLabel.setText("Enter Item ID:");

        saleQtyLabel.setText("Enter Quantity:");

        saleAddButton.setText("Add Item");
        saleAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleAddButtonActionPerformed(evt);
            }
        });

        saleCancelButton.setText("Cancel");
        saleCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleCancelButtonActionPerformed(evt);
            }
        });

        saleRemoveButton.setText("Remove Item");
        saleRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleRemoveButtonActionPerformed(evt);
            }
        });

        saleTotalLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        saleTotalLabel.setText("Total:");

        saleRemoveLabl.setText("Line to Remove:");

        javax.swing.GroupLayout salePanelLayout = new javax.swing.GroupLayout(salePanel);
        salePanel.setLayout(salePanelLayout);
        salePanelLayout.setHorizontalGroup(
            salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salePanelLayout.createSequentialGroup()
                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salePanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(saleAddButton))
                    .addGroup(salePanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(saleRemoveButton))
                    .addGroup(salePanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salePanelLayout.createSequentialGroup()
                                .addComponent(saleRemoveLabl)
                                .addGap(18, 18, 18)
                                .addComponent(saleRemoveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salePanelLayout.createSequentialGroup()
                                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(saleQtyLabel)
                                    .addComponent(saleIdLabel))
                                .addGap(18, 18, 18)
                                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saleQtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(saleIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salePanelLayout.createSequentialGroup()
                        .addComponent(saleCartLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(salePanelLayout.createSequentialGroup()
                        .addComponent(saleTotalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(saleCancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saleCheckoutButton)))
                .addContainerGap())
            .addGroup(salePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(saleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        salePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {saleAddButton, saleIdTextField, saleQtyTextField, saleRemoveButton, saleRemoveTextField});

        salePanelLayout.setVerticalGroup(
            salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(saleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saleCartLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(salePanelLayout.createSequentialGroup()
                        .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saleIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saleIdLabel))
                        .addGap(18, 18, 18)
                        .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saleQtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saleQtyLabel))
                        .addGap(18, 18, 18)
                        .addComponent(saleAddButton)
                        .addGap(18, 18, 18)
                        .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saleRemoveLabl)
                            .addComponent(saleRemoveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(saleRemoveButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saleCheckoutButton)
                    .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saleTotalLabel)
                        .addComponent(saleCancelButton)))
                .addGap(10, 10, 10))
        );

        getContentPane().add(salePanel, "card3");

        itemAddErrorLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        itemAddErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemAddErrorLabel.setText("Error: Item ID not found");

        itemAddOkButton.setText("OK");
        itemAddOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddOkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saleItemAddErrorPanelLayout = new javax.swing.GroupLayout(saleItemAddErrorPanel);
        saleItemAddErrorPanel.setLayout(saleItemAddErrorPanelLayout);
        saleItemAddErrorPanelLayout.setHorizontalGroup(
            saleItemAddErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saleItemAddErrorPanelLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(saleItemAddErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemAddErrorLabel)
                    .addComponent(itemAddOkButton))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        saleItemAddErrorPanelLayout.setVerticalGroup(
            saleItemAddErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saleItemAddErrorPanelLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(itemAddErrorLabel)
                .addGap(18, 18, 18)
                .addComponent(itemAddOkButton)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        getContentPane().add(saleItemAddErrorPanel, "card7");

        removeErrorLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        removeErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removeErrorLabel.setText("Error: Invalid index given");

        removeErrorOkButton.setText("OK");
        removeErrorOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeErrorOkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saleRemoveErrorPanelLayout = new javax.swing.GroupLayout(saleRemoveErrorPanel);
        saleRemoveErrorPanel.setLayout(saleRemoveErrorPanelLayout);
        saleRemoveErrorPanelLayout.setHorizontalGroup(
            saleRemoveErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saleRemoveErrorPanelLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(saleRemoveErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeErrorOkButton)
                    .addComponent(removeErrorLabel))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        saleRemoveErrorPanelLayout.setVerticalGroup(
            saleRemoveErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saleRemoveErrorPanelLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(removeErrorLabel)
                .addGap(18, 18, 18)
                .addComponent(removeErrorOkButton)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        getContentPane().add(saleRemoveErrorPanel, "card7");

        rentLabel.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        rentLabel.setText("New Rental");

        rentCartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Description", "Unit Price", "Quantity", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(rentCartTable);

        rentCheckoutButton.setText("Checkout");
        rentCheckoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentCheckoutButtonActionPerformed(evt);
            }
        });

        rentCartLabel.setText("Customer Cart");

        rentIdLabel.setText("Enter Item ID:");

        rentQtyLabel.setText("Enter Quantity:");

        rentAddButton.setText("Add Item");
        rentAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentAddButtonActionPerformed(evt);
            }
        });

        rentCancelButton.setText("Cancel");
        rentCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentCancelButtonActionPerformed(evt);
            }
        });

        rentRemoveButton.setText("Remove Item");
        rentRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentRemoveButtonActionPerformed(evt);
            }
        });

        rentTotalLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        rentTotalLabel.setText("Total:");

        rentRemoveLabel.setText("Line to Remove:");

        rentPeriodLabel.setText("Rental Period:");

        javax.swing.GroupLayout rentPanelLayout = new javax.swing.GroupLayout(rentPanel);
        rentPanel.setLayout(rentPanelLayout);
        rentPanelLayout.setHorizontalGroup(
            rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentPanelLayout.createSequentialGroup()
                .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rentPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(rentAddButton))
                    .addGroup(rentPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(rentRemoveButton))
                    .addGroup(rentPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rentPanelLayout.createSequentialGroup()
                                .addComponent(rentRemoveLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rentRemoveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rentPanelLayout.createSequentialGroup()
                                .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rentQtyLabel)
                                    .addComponent(rentIdLabel))
                                .addGap(18, 18, 18)
                                .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rentQtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rentIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(rentPanelLayout.createSequentialGroup()
                        .addComponent(rentTotalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(rentCancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rentCheckoutButton))
                    .addGroup(rentPanelLayout.createSequentialGroup()
                        .addComponent(rentCartLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rentPeriodLabel)
                        .addGap(55, 55, 55)))
                .addContainerGap())
            .addGroup(rentPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(rentLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rentPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rentIdTextField, rentQtyTextField, rentRemoveTextField});

        rentPanelLayout.setVerticalGroup(
            rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rentPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rentLabel)
                .addGap(18, 18, 18)
                .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentCartLabel)
                    .addComponent(rentPeriodLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rentPanelLayout.createSequentialGroup()
                        .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rentIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rentIdLabel))
                        .addGap(18, 18, 18)
                        .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rentQtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rentQtyLabel))
                        .addGap(18, 18, 18)
                        .addComponent(rentAddButton)
                        .addGap(18, 18, 18)
                        .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rentRemoveLabel)
                            .addComponent(rentRemoveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(rentRemoveButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rentCheckoutButton)
                    .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rentTotalLabel)
                        .addComponent(rentCancelButton)))
                .addGap(10, 10, 10))
        );

        getContentPane().add(rentPanel, "card3");

        rentPeriodPanelLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        rentPeriodPanelLabel.setText("Rental Period:");

        rentPeriodSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), null, Integer.valueOf(14), Integer.valueOf(1)));

        rentPeriodSetButton.setText("Set");
        rentPeriodSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentPeriodSetButtonActionPerformed(evt);
            }
        });

        rentPeriodCancelButton.setText("Cancel");
        rentPeriodCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentPeriodCancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Days");

        javax.swing.GroupLayout rentPeriodPanelLayout = new javax.swing.GroupLayout(rentPeriodPanel);
        rentPeriodPanel.setLayout(rentPeriodPanelLayout);
        rentPeriodPanelLayout.setHorizontalGroup(
            rentPeriodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentPeriodPanelLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(rentPeriodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(rentPeriodPanelLayout.createSequentialGroup()
                        .addComponent(rentPeriodCancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rentPeriodSetButton))
                    .addGroup(rentPeriodPanelLayout.createSequentialGroup()
                        .addComponent(rentPeriodPanelLabel)
                        .addGap(34, 34, 34)
                        .addComponent(rentPeriodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        rentPeriodPanelLayout.setVerticalGroup(
            rentPeriodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentPeriodPanelLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(rentPeriodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentPeriodPanelLabel)
                    .addComponent(rentPeriodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(rentPeriodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rentPeriodSetButton)
                    .addComponent(rentPeriodCancelButton))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        getContentPane().add(rentPeriodPanel, "card7");

        cashButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cashButton.setText("Cash");
        cashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashButtonActionPerformed(evt);
            }
        });

        creditButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        creditButton.setText("Credit");

        javax.swing.GroupLayout cashOrCreditPanelLayout = new javax.swing.GroupLayout(cashOrCreditPanel);
        cashOrCreditPanel.setLayout(cashOrCreditPanelLayout);
        cashOrCreditPanelLayout.setHorizontalGroup(
            cashOrCreditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashOrCreditPanelLayout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(cashButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(creditButton)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        cashOrCreditPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cashButton, creditButton});

        cashOrCreditPanelLayout.setVerticalGroup(
            cashOrCreditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashOrCreditPanelLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(cashOrCreditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditButton))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        cashOrCreditPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cashButton, creditButton});

        getContentPane().add(cashOrCreditPanel, "card8");

        calcChangeButton.setText("Calculate Change");
        calcChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcChangeButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Cash Received: ");

        cashPanelCancelButton.setText("Cancel");
        cashPanelCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashPanelCancelButtonActionPerformed(evt);
            }
        });

        changeLabel.setText("Change: $");

        cashDoneButton.setText("Done");
        cashDoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashDoneButtonActionPerformed(evt);
            }
        });

        cashTotalLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        cashTotalLabel.setText("Total:");

        javax.swing.GroupLayout cashPanelLayout = new javax.swing.GroupLayout(cashPanel);
        cashPanel.setLayout(cashPanelLayout);
        cashPanelLayout.setHorizontalGroup(
            cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashPanelLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashErrorLabel)
                    .addComponent(cashTotalLabel)
                    .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(cashPanelLayout.createSequentialGroup()
                            .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cashPanelCancelButton)
                                .addGroup(cashPanelLayout.createSequentialGroup()
                                    .addComponent(changeLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(changeAmountLabel)))
                            .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(cashPanelLayout.createSequentialGroup()
                                    .addGap(125, 125, 125)
                                    .addComponent(cashDoneButton))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cashPanelLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(calcChangeButton))))
                        .addGroup(cashPanelLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cashReceivedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        cashPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {changeAmountLabel, changeLabel});

        cashPanelLayout.setVerticalGroup(
            cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cashPanelLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(cashTotalLabel)
                .addGap(18, 18, 18)
                .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashReceivedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcChangeButton)
                    .addComponent(cashPanelCancelButton))
                .addGap(14, 14, 14)
                .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashDoneButton)
                    .addComponent(changeLabel)
                    .addComponent(changeAmountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cashErrorLabel)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        getContentPane().add(cashPanel, "card9");

        rentRemoveErrorLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        rentRemoveErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rentRemoveErrorLabel.setText("Error: Invalid index given");

        rentRemoveErrorButton.setText("OK");
        rentRemoveErrorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentRemoveErrorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rentRemoveErrorPanelLayout = new javax.swing.GroupLayout(rentRemoveErrorPanel);
        rentRemoveErrorPanel.setLayout(rentRemoveErrorPanelLayout);
        rentRemoveErrorPanelLayout.setHorizontalGroup(
            rentRemoveErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentRemoveErrorPanelLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(rentRemoveErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rentRemoveErrorButton)
                    .addComponent(rentRemoveErrorLabel))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        rentRemoveErrorPanelLayout.setVerticalGroup(
            rentRemoveErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentRemoveErrorPanelLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(rentRemoveErrorLabel)
                .addGap(18, 18, 18)
                .addComponent(rentRemoveErrorButton)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        getContentPane().add(rentRemoveErrorPanel, "card7");

        rentItemAddErrorLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        rentItemAddErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rentItemAddErrorLabel.setText("Error: Item ID not found");

        rentItemAddErrorButton.setText("OK");
        rentItemAddErrorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentItemAddErrorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rentItemAddErrorPanelLayout = new javax.swing.GroupLayout(rentItemAddErrorPanel);
        rentItemAddErrorPanel.setLayout(rentItemAddErrorPanelLayout);
        rentItemAddErrorPanelLayout.setHorizontalGroup(
            rentItemAddErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentItemAddErrorPanelLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(rentItemAddErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rentItemAddErrorLabel)
                    .addComponent(rentItemAddErrorButton))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        rentItemAddErrorPanelLayout.setVerticalGroup(
            rentItemAddErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rentItemAddErrorPanelLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(rentItemAddErrorLabel)
                .addGap(18, 18, 18)
                .addComponent(rentItemAddErrorButton)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        getContentPane().add(rentItemAddErrorPanel, "card7");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startSaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startSaleButtonActionPerformed
        r.makeNewSale();
        // set the total label to the new total
        String total = String.format("Total: $%4.2f", r.getCurrentTransaction().getTotal().getAmount().doubleValue());
        saleTotalLabel.setText(total);
        menuPanel.setVisible(false);
        salePanel.setVisible(true);
    }//GEN-LAST:event_startSaleButtonActionPerformed

    private void saleCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleCancelButtonActionPerformed
        // cancel transaction
        r.cancelTransaction();

        // reset table
        DefaultTableModel model = (DefaultTableModel) saleCartTable.getModel();
        model.setRowCount(0);

        // clear text fields
        saleIdTextField.setText("");
        saleQtyTextField.setText("");
        saleRemoveTextField.setText("");

        // switch back to menu view
        salePanel.setVisible(false);
        menuPanel.setVisible(true);
    }//GEN-LAST:event_saleCancelButtonActionPerformed

    private void startRentalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startRentalButtonActionPerformed
        menuPanel.setVisible(false);
        rentPeriodPanel.setVisible(true);
    }//GEN-LAST:event_startRentalButtonActionPerformed

    private void saleAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleAddButtonActionPerformed
        // get id and quantity for line item
        try {
            Integer id = Integer.parseInt(saleIdTextField.getText());
            Integer qty = Integer.parseInt(saleQtyTextField.getText());

            // get table model from saleCartTable
            DefaultTableModel model = (DefaultTableModel) saleCartTable.getModel();

            // create and add line item to sale
            try {
                LineItem currentLineItem = r.enterItem(id, qty);
                ProductDescription currentProductDescription = currentLineItem.getProductDescription();

                // add line item to table
                String desc = currentProductDescription.getDescription();

                double price = currentProductDescription.getPrice().getAmount().doubleValue();
                String priceString = String.format("$%4.2f", price);
                String qtyString = qty.toString();
                double subtotal = currentLineItem.getSubtotal().getAmount().doubleValue();
                String subtotalString = String.format("$%4.2f", subtotal);

                Object[] row = {desc, priceString, qtyString, subtotalString};
                model.addRow(row);

                // set the total label to the new total
                String total = String.format("Total: $%4.2f", r.getCurrentTransaction().getTotal().getAmount().doubleValue());
                saleTotalLabel.setText(total);

                // clear text fields
                saleIdTextField.setText("");
                saleQtyTextField.setText("");
            } catch (NullPointerException ex) {
                salePanel.setVisible(false);
                saleItemAddErrorPanel.setVisible(true);
            }
        } catch (NumberFormatException ex) {
        }
    }//GEN-LAST:event_saleAddButtonActionPerformed

    private void itemAddOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddOkButtonActionPerformed
        saleItemAddErrorPanel.setVisible(false);
        salePanel.setVisible(true);
    }//GEN-LAST:event_itemAddOkButtonActionPerformed

    private void saleRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleRemoveButtonActionPerformed
        // get index of line to remove
        try {
            Integer row = Integer.parseInt(saleRemoveTextField.getText()) - 1;

            // get table model from saleCartTable
            DefaultTableModel model = (DefaultTableModel) saleCartTable.getModel();

            try {
                // remove line from currentTransaction and from table
                r.getCurrentTransaction().removeLineItem(row);
                model.removeRow(row);

                // update total
                String total = String.format("Total: $%4.2f", r.getCurrentTransaction().getTotal().getAmount().doubleValue());
                saleTotalLabel.setText(total);

                // reset text field
                saleRemoveTextField.setText("");
            } catch (IndexOutOfBoundsException ex) {
                salePanel.setVisible(false);
                saleRemoveErrorPanel.setVisible(true);
            }
        } catch (NumberFormatException ex) {
        }
        // clear line to remove text
    }//GEN-LAST:event_saleRemoveButtonActionPerformed

    private void removeErrorOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeErrorOkButtonActionPerformed
        saleRemoveErrorPanel.setVisible(false);
        salePanel.setVisible(true);
    }//GEN-LAST:event_removeErrorOkButtonActionPerformed

    private void saleCheckoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleCheckoutButtonActionPerformed
        // end sale to update inventory and add transaction to database
        //r.endTransaction();

        // clear text fields
        saleIdTextField.setText("");
        saleQtyTextField.setText("");
        saleRemoveTextField.setText("");

        // reset table
        DefaultTableModel model = (DefaultTableModel) saleCartTable.getModel();
        model.setRowCount(0);

        // set total label in cashPanel
        String total = String.format("Total: $%4.2f", r.getCurrentTransaction().getTotal().getAmount().doubleValue());
        cashTotalLabel.setText(total);

        // prompt for cash or credit
        cashOrCreditPanel.setVisible(true);
        salePanel.setVisible(false);
    }//GEN-LAST:event_saleCheckoutButtonActionPerformed

    private void rentCheckoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentCheckoutButtonActionPerformed
        // clear text fields
        rentIdTextField.setText("");
        rentQtyTextField.setText("");
        rentRemoveTextField.setText("");

        // return to menu view
        rentPanel.setVisible(false);
        cashOrCreditPanel.setVisible(true);
    }//GEN-LAST:event_rentCheckoutButtonActionPerformed

    private void rentAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentAddButtonActionPerformed
        // get id and quantity for line item
        try {
            Integer id = Integer.parseInt(rentIdTextField.getText());
            Integer qty = Integer.parseInt(rentQtyTextField.getText());

            // get table model from saleCartTable
            DefaultTableModel model = (DefaultTableModel) rentCartTable.getModel();

            // create and add line item to sale
            try {
                LineItem currentLineItem = r.enterItem(id, qty);
                ProductDescription currentProductDescription = currentLineItem.getProductDescription();

                // add line item to table
                String desc = currentProductDescription.getDescription();

                double price = currentProductDescription.getPrice().getAmount().doubleValue();
                String priceString = String.format("$%4.2f", price);
                String qtyString = qty.toString();
                double subtotal = currentLineItem.getSubtotal().getAmount().doubleValue();
                String subtotalString = String.format("$%4.2f", subtotal);

                Object[] row = {desc, priceString, qtyString, subtotalString};
                model.addRow(row);

                // set the total label to the new total
                String total = String.format("Total: $%4.2f", r.getCurrentTransaction().getTotal().getAmount().doubleValue());
                rentTotalLabel.setText(total);

                // clear text fields
                rentIdTextField.setText("");
                rentQtyTextField.setText("");
            } catch (NullPointerException ex) {
                rentPanel.setVisible(false);
                rentItemAddErrorPanel.setVisible(true);
            }
        } catch (NumberFormatException ex) {
        }

    }//GEN-LAST:event_rentAddButtonActionPerformed

    private void rentCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentCancelButtonActionPerformed
        // cancel transaction
        r.cancelTransaction();

        // reset table
        DefaultTableModel model = (DefaultTableModel) rentCartTable.getModel();
        model.setRowCount(0);

        // reset total
        rentTotalLabel.setText("Total:");

        // clear text fields
        rentIdTextField.setText("");
        rentQtyTextField.setText("");
        rentRemoveTextField.setText("");

        // switch back to menu view
        rentPanel.setVisible(false);
        menuPanel.setVisible(true);
    }//GEN-LAST:event_rentCancelButtonActionPerformed

    private void rentRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentRemoveButtonActionPerformed
        // get index of line to remove
        try {
            Integer row = Integer.parseInt(rentRemoveTextField.getText()) - 1;

            // get table model from saleCartTable
            DefaultTableModel model = (DefaultTableModel) rentCartTable.getModel();

            try {
                // remove line from currentTransaction and from table
                r.getCurrentTransaction().removeLineItem(row);
                model.removeRow(row);

                // update total
                String total = String.format("Total: $%4.2f", r.getCurrentTransaction().getTotal().getAmount().doubleValue());
                rentTotalLabel.setText(total);

                // reset text field
                rentRemoveTextField.setText("");
            } catch (IndexOutOfBoundsException ex) {
                rentPanel.setVisible(false);
                rentRemoveErrorPanel.setVisible(true);
            }
        } catch (NumberFormatException ex) {
        }
        // clear line to remove text
    }//GEN-LAST:event_rentRemoveButtonActionPerformed

    private void rentPeriodCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentPeriodCancelButtonActionPerformed
        // reset spinner
        rentPeriodSpinner.setValue(1);

        // switch back to main menu view
        rentPeriodPanel.setVisible(false);
        menuPanel.setVisible(true);
    }//GEN-LAST:event_rentPeriodCancelButtonActionPerformed

    private void rentPeriodSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentPeriodSetButtonActionPerformed
        // get return period from spinner
        Integer numDays = (Integer) rentPeriodSpinner.getValue();

        // create new rental transaction
        r.makeNewRental(numDays);

        // reset spinner
        rentPeriodSpinner.setValue(1);

        // switch to rental view
        rentPeriodPanel.setVisible(false);
        rentPanel.setVisible(true);

        // set rental period in rentPanel to rental period provided
        rentPeriodLabel.setText("Rental Period: " + numDays + " days");
    }//GEN-LAST:event_rentPeriodSetButtonActionPerformed

    private void cashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashButtonActionPerformed
        // set total on cash panel
        String total = String.format("Total: $%4.2f", r.getCurrentTransaction().getTotal().getAmount().doubleValue());
        cashTotalLabel.setText(total);

        // switch to cash payment view
        cashOrCreditPanel.setVisible(false);
        cashPanel.setVisible(true);
    }//GEN-LAST:event_cashButtonActionPerformed

    private void calcChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcChangeButtonActionPerformed
        try {
            // get cash received
            Double cashReceived = Double.parseDouble(cashReceivedTextField.getText());

            // create a new payment to verify with transaction
            r.setCurrentPayment(new CashPayment(cashReceived));
            System.out.println("cash given: " + ((CashPayment) r.getCurrentPayment()).getCashGiven().getAmount().doubleValue());
            if (r.getCurrentTransaction().accept(r.getCurrentPayment())) {
                System.out.println("change: " + ((CashPayment) r.getCurrentPayment()).getChange().getAmount().doubleValue());
                String changeString = String.format("%4.2f", ((CashPayment) r.getCurrentPayment()).getChange().getAmount());
                changeAmountLabel.setText(changeString);
            } else {
                changeAmountLabel.setText("Insufficient Funds");
            }
        } catch (NumberFormatException ex) {
        }
    }//GEN-LAST:event_calcChangeButtonActionPerformed

    private void cashDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashDoneButtonActionPerformed
        // check if current payment is acceptable
        if (r.getCurrentTransaction().accept(r.getCurrentPayment())) {
            // end sale
            r.endTransaction();

            // return to menu view
            cashPanel.setVisible(false);
            menuPanel.setVisible(true);

            // reset sale table
            DefaultTableModel saleModel = (DefaultTableModel) saleCartTable.getModel();
            saleModel.setRowCount(0);

            // clear cash text fields
            cashReceivedTextField.setText("");
            changeAmountLabel.setText("");
            cashErrorLabel.setText("");

            // reset rent table
            DefaultTableModel rentModel = (DefaultTableModel) rentCartTable.getModel();
            rentModel.setRowCount(0);

        } else {
            cashErrorLabel.setText("Insufficient funds to complete sale");
        }

    }//GEN-LAST:event_cashDoneButtonActionPerformed

    private void cashPanelCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashPanelCancelButtonActionPerformed
        // cancel transaction
        r.cancelTransaction();

        // clear all cashPanel text
        // return to menu view
        cashPanel.setVisible(false);
        menuPanel.setVisible(true);

        // clear text fields
        cashReceivedTextField.setText("");
        changeAmountLabel.setText("");
        cashErrorLabel.setText("");

        // reset rent table
        DefaultTableModel rentModel = (DefaultTableModel) rentCartTable.getModel();
        rentModel.setRowCount(0);

        // reset sale table
        DefaultTableModel saleModel = (DefaultTableModel) saleCartTable.getModel();
        saleModel.setRowCount(0);
    }//GEN-LAST:event_cashPanelCancelButtonActionPerformed

    private void rentRemoveErrorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentRemoveErrorButtonActionPerformed
        // change back to rental view
        rentRemoveErrorPanel.setVisible(false);
        rentPanel.setVisible(true);
    }//GEN-LAST:event_rentRemoveErrorButtonActionPerformed

    private void rentItemAddErrorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentItemAddErrorButtonActionPerformed
        // change back to rental view
        rentItemAddErrorPanel.setVisible(false);
        rentPanel.setVisible(true);
    }//GEN-LAST:event_rentItemAddErrorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcChangeButton;
    private javax.swing.JButton cashButton;
    private javax.swing.JButton cashDoneButton;
    private javax.swing.JLabel cashErrorLabel;
    private javax.swing.JPanel cashOrCreditPanel;
    private javax.swing.JPanel cashPanel;
    private javax.swing.JButton cashPanelCancelButton;
    private javax.swing.JTextField cashReceivedTextField;
    private javax.swing.JLabel cashTotalLabel;
    private javax.swing.JLabel changeAmountLabel;
    private javax.swing.JLabel changeLabel;
    private javax.swing.JButton creditButton;
    private javax.swing.JLabel itemAddErrorLabel;
    private javax.swing.JButton itemAddOkButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel removeErrorLabel;
    private javax.swing.JButton removeErrorOkButton;
    private javax.swing.JButton rentAddButton;
    private javax.swing.JButton rentCancelButton;
    private javax.swing.JLabel rentCartLabel;
    private javax.swing.JTable rentCartTable;
    private javax.swing.JButton rentCheckoutButton;
    private javax.swing.JLabel rentIdLabel;
    private javax.swing.JTextField rentIdTextField;
    private javax.swing.JButton rentItemAddErrorButton;
    private javax.swing.JLabel rentItemAddErrorLabel;
    private javax.swing.JPanel rentItemAddErrorPanel;
    private javax.swing.JLabel rentLabel;
    private javax.swing.JPanel rentPanel;
    private javax.swing.JButton rentPeriodCancelButton;
    private javax.swing.JLabel rentPeriodLabel;
    private javax.swing.JPanel rentPeriodPanel;
    private javax.swing.JLabel rentPeriodPanelLabel;
    private javax.swing.JButton rentPeriodSetButton;
    private javax.swing.JSpinner rentPeriodSpinner;
    private javax.swing.JLabel rentQtyLabel;
    private javax.swing.JTextField rentQtyTextField;
    private javax.swing.JButton rentRemoveButton;
    private javax.swing.JButton rentRemoveErrorButton;
    private javax.swing.JLabel rentRemoveErrorLabel;
    private javax.swing.JPanel rentRemoveErrorPanel;
    private javax.swing.JLabel rentRemoveLabel;
    private javax.swing.JTextField rentRemoveTextField;
    private javax.swing.JLabel rentTotalLabel;
    private javax.swing.JButton saleAddButton;
    private javax.swing.JButton saleCancelButton;
    private javax.swing.JLabel saleCartLabel;
    private javax.swing.JTable saleCartTable;
    private javax.swing.JButton saleCheckoutButton;
    private javax.swing.JLabel saleIdLabel;
    private javax.swing.JTextField saleIdTextField;
    private javax.swing.JPanel saleItemAddErrorPanel;
    private javax.swing.JLabel saleLabel;
    private javax.swing.JPanel salePanel;
    private javax.swing.JLabel saleQtyLabel;
    private javax.swing.JTextField saleQtyTextField;
    private javax.swing.JButton saleRemoveButton;
    private javax.swing.JPanel saleRemoveErrorPanel;
    private javax.swing.JLabel saleRemoveLabl;
    private javax.swing.JTextField saleRemoveTextField;
    private javax.swing.JLabel saleTotalLabel;
    private javax.swing.JButton startRentalButton;
    private javax.swing.JButton startReturnButton;
    private javax.swing.JButton startSaleButton;
    private javax.swing.JButton userManagementButton;
    // End of variables declaration//GEN-END:variables
}
